name: fitness
description: A fitness app project
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.0.1
  flutter_bloc: ^3.1.0
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  http: ^0.12.0+4
  line_awesome_icons: ^1.0.4+2
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^1.7.3
  hive_generator: ^0.7.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-Italic.ttf
          style: italic